/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.br.irecovery.view;

import com.br.irecovery.controller.IRecoveryController;
import com.br.irecovery.models.ComboDeviceRenderer;
import com.br.irecovery.models.ComboImageRenderer;
import com.br.irecovery.models.Device;
import com.br.irecovery.models.Devices;
import com.br.irecovery.models.Image;
import com.br.irecovery.rest.ImageRest;
import com.br.irecovery.util.Log;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;

/**
 *
 * @author ailson
 */
public class iRecovery extends javax.swing.JFrame {
    Devices devices;
    private ArrayList<Image> images;
    private static String tmpdir = System.getProperty("java.io.tmpdir");
    
    /**
     * Creates new form iRecovery
     */
    public iRecovery() {
        initComponents();
        setIcon();
        loadLog();
        loadDevices();
        loadImages();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        comboxDevices = new javax.swing.JComboBox();
        start = new javax.swing.JButton();
        message = new javax.swing.JLabel();
        jLabeldevice = new javax.swing.JLabel();
        jLabelimage = new javax.swing.JLabel();
        comboxImages = new javax.swing.JComboBox();
        jProgressBar1 = new javax.swing.JProgressBar();
        loadDevice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("iRecovery");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        start.setText("Iniciar");
        start.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startActionPerformed(evt);
            }
        });

        message.setText("mensagem");

        jLabeldevice.setText("Dispositivo");

        jLabelimage.setText("Imagem");

        loadDevice.setText("Carregar");
        loadDevice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadDeviceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(start, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(comboxDevices, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(comboxImages, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(loadDevice))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabeldevice)
                            .addComponent(jLabelimage))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jProgressBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                    .addComponent(message, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addComponent(jLabeldevice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboxDevices, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadDevice))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelimage)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(comboxImages, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(message)
                .addGap(18, 18, 18)
                .addComponent(start)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loadDeviceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadDeviceActionPerformed
        loadDevices();
        loadImages();
    }//GEN-LAST:event_loadDeviceActionPerformed

    private void startActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startActionPerformed
        try {
            Object selectedDevice = comboxDevices.getSelectedItem();
            Object selectedImage = comboxImages.getSelectedItem();
            
            Device device = (Device)selectedDevice;
            Image image = (Image)selectedImage;
            
            if (device != null && image != null) {
                IRecoveryController.run(device, image, start, message, jProgressBar1);
            }
        } catch (Exception ex) {
                start.setEnabled(true);
                Logger.getLogger(iRecovery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_startActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(iRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(iRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(iRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(iRecovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new iRecovery().setVisible(true);
            }
        });
    }
    
    private void setIcon() {
        try {
            setIconImage(ImageIO.read(getClass().getResourceAsStream("/com/br/irecovery/images/pendrive.png")));
        } catch (IOException ex) {
            Logger.getLogger(iRecovery.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private void loadLog(){
        try {
            Log.setup();
	} catch (IOException e) {
            e.printStackTrace();
        }
    }
    
    public void loadDevices(){	
        boolean empty = true;
        comboxDevices.removeAllItems();
     	devices = new Devices();
        devices.setDevices();
        start.setEnabled(true);
        comboxDevices.setEnabled(true);
        
        for (Device device : devices.getDevices()) {
            comboxDevices.addItem(device);
	    empty = false;
        }
        
        comboxDevices.setRenderer(new ComboDeviceRenderer());
        
        if (empty) {
            start.setEnabled(false);
            comboxDevices.setEnabled(false);
            message.setText("Não tem dispositivo");
        } else {
            message.setText("Aguardando...");
        }
    }
    
    private void loadImages(){
        boolean empty = true;
        comboxImages.removeAllItems();
        images = new ArrayList();
        start.setEnabled(true);
        comboxImages.setEnabled(true);
        
        try {
            images = ImageRest.getImages();
        } catch (Exception ex) {
            Logger.getLogger(iRecovery.class.getName()).log(Level.SEVERE, null, ex);
        }

        Log.setLog(Level.INFO, "Imagem: " + images.toString());
       
        for (Image image : images) {
            comboxImages.addItem(image);
	    empty = false;
        }
       
        if (empty) {
            start.setEnabled(false);
            comboxDevices.setEnabled(false);
            message.setText("Sem Imagem, informe o administrador");
        } else {
            message.setText("Aguardando...");
        }
        comboxImages.setRenderer(new ComboImageRenderer());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox comboxDevices;
    private javax.swing.JComboBox comboxImages;
    private javax.swing.JLabel jLabeldevice;
    private javax.swing.JLabel jLabelimage;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JButton loadDevice;
    private javax.swing.JLabel message;
    private javax.swing.JButton start;
    // End of variables declaration//GEN-END:variables
}
